In [1]:
import json

import matplotlib.pyplot as plt
import os
import pandas as pd
import numpy as np
from   collections import defaultdict
import string

In [2]:
data= pd.read_csv('datasets/population-clean.csv')
data_solutions = pd.read_csv('datasets/solutions-clean.csv')

In [3]:
data.head()

,year,origin_country,origin_iso,asylum_country,asylum_iso,number_refugees,number_asylum,idps_concern,venezuelans_displaced,stateless,of_concern
0,2010,Afghanistan,AFG,Afghanistan,AFG,0,0,351907,NaN,0,838250
1,2010,Iran (Islamic Rep. of),IRN,Afghanistan,AFG,30,21,0,NaN,0,0
2,2010,Iraq,IRQ,Afghanistan,AFG,6,0,0,NaN,0,0
3,2010,Pakistan,PAK,Afghanistan,AFG,6398,9,0,NaN,0,0
4,2010,Egypt,EGY,Albania,ALB,5,0,0,NaN,0,0

In [4]:
data_solutions.head()

,year,origin_country,origin_iso,asylum_country,asylum_iso,returned_refugees,returned_idpss,resettlement_arrivals,naturalisation
0,2010,Afghanistan,AFG,Afghanistan,AFG,NaN,3366.0,NaN,NaN
1,2010,Iraq,IRQ,Egypt,EGY,243.0,NaN,NaN,NaN
2,2010,Somalia,SOM,Egypt,EGY,12.0,NaN,NaN,NaN
3,2010,Sudan,SDN,Egypt,EGY,251.0,NaN,NaN,NaN
4,2010,Colombia,COL,Argentina,ARG,NaN,NaN,15.0,NaN

In [5]:
data_2013 = data[data['year']==2013]

data_2013.head()

,year,origin_country,origin_iso,asylum_country,asylum_iso,number_refugees,number_asylum,idps_concern,venezuelans_displaced,stateless,of_concern
12776,2013,Afghanistan,AFG,Afghanistan,AFG,0,0,631286,NaN,0,275486
12777,2013,Iran (Islamic Rep. of),IRN,Afghanistan,AFG,36,16,0,NaN,0,0
12778,2013,Pakistan,PAK,Afghanistan,AFG,16825,45,0,NaN,0,0
12779,2013,Egypt,EGY,Albania,ALB,5,0,0,NaN,0,0
12780,2013,China,CHN,Albania,ALB,12,0,0,NaN,0,0

In [6]:
solutions_2013 = data_solutions[data_solutions['year'] ==2013]
solutions_2013.head()

,year,origin_country,origin_iso,asylum_country,asylum_iso,returned_refugees,returned_idpss,resettlement_arrivals,naturalisation
1639,2013,Afghanistan,AFG,Afghanistan,AFG,NaN,21830.0,NaN,NaN
1640,2013,Palestinian,PSE,Algeria,DZA,5.0,NaN,NaN,NaN
1641,2013,Mali,MLI,Algeria,DZA,921.0,NaN,NaN,NaN
1642,2013,Rwanda,RWA,Angola,AGO,7.0,NaN,NaN,NaN
1643,2013,Ethiopia,ETH,Egypt,EGY,5.0,NaN,NaN,NaN

In [16]:
# data_2013['origin_country'].replace('Syrian Arab Rep.', 'Syria')
data_2013.loc[:, 'origin_country']=data_2013.loc[:, 'origin_country'].replace({'Syrian Arab Rep.':'Syria', 
                                                                               'Russian Federation': 'Russia', 
                                                                               'Iran (Islamic Rep. of)': 'Iran', 
                                                                               'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom', 
                                                                               'Viet Nam': 'Vietnam', 'Palestinian': 'Palestine', 'Rep. of Korea': 'South Korea', 
                                                                               "Dem. People's Rep. of Korea": "North Korea", 'Bolivia (Plurinational State of)': 'Bolivia', 
                                                                               'China, Hong Kong SAR': 'Hong Kong', 'Denmark': 'Greenland', 'Rep. of Moldova': 'Moldova', 
                                                                               'United Rep. of Tanzania': 'Tanzania', 'Eswatini': 'eSwatini', 
                                                                               "Cote d'Ivoire": "Côte d'Ivoire", 'Serbia and Kosovo: S/RES/1244 (1999)': 'Serbia', 
                                                                               'Venezuela (Bolivarian Republic of)': 'Venezuela', 'Dem. Rep. of the Congo': 'Dem. Rep. Congo', 
                                                                               "Lao People's Dem. Rep.": 'Laos',
                                                                              "South Sudan": "S. Sudan", 
                                                                              "West Sahara": "W. Sahara", 
                                                                              "Bosnia and Herzegovina": "Bosnia and Herz"})

data_2013.loc[:, 'asylum_country']=data_2013.loc[:, 'asylum_country'].replace({'Syrian Arab Rep.':'Syria', 
                                                                               'Russian Federation': 'Russia', 
                                                                               'Iran (Islamic Rep. of)': 'Iran', 
                                                                               'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom', 
                                                                               'Viet Nam': 'Vietnam', 'Palestinian': 'Palestine', 'Rep. of Korea': 'South Korea', 
                                                                               "Dem. People's Rep. of Korea": "North Korea", 'Bolivia (Plurinational State of)': 'Bolivia', 
                                                                               'China, Hong Kong SAR': 'Hong Kong', 'Denmark': 'Greenland', 'Rep. of Moldova': 'Moldova', 
                                                                               'United Rep. of Tanzania': 'Tanzania', 'Eswatini': 'eSwatini', 
                                                                               "Cote d'Ivoire": "Côte d'Ivoire", 'Serbia and Kosovo: S/RES/1244 (1999)': 'Serbia', 
                                                                               'Venezuela (Bolivarian Republic of)': 'Venezuela', 'Dem. Rep. of the Congo': 'Dem. Rep. Congo', 
                                                                               "Lao People's Dem. Rep.": 'Laos',
                                                                              "South Sudan": "S. Sudan", 
                                                                              "West Sahara": "W. Sahara", 
                                                                              "Bosnia and Herzegovina": "Bosnia and Herz", 
                                                                               "United States of America": "USA"
                                                                              })

/Users/yunyunwang/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [ ]:
solutions_2013.loc[:, 'origin_country']=solutions_2013.loc[:, 'origin_country'].replace({'Syrian Arab Rep.':'Syria', 
                                                                               'Russian Federation': 'Russia', 
                                                                               'Iran (Islamic Rep. of)': 'Iran', 
                                                                               'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom', 
                                                                               'Viet Nam': 'Vietnam', 'Palestinian': 'Palestine', 'Rep. of Korea': 'South Korea', 
                                                                               "Dem. People's Rep. of Korea": "North Korea", 'Bolivia (Plurinational State of)': 'Bolivia', 
                                                                               'China, Hong Kong SAR': 'Hong Kong', 'Denmark': 'Greenland', 'Rep. of Moldova': 'Moldova', 
                                                                               'United Rep. of Tanzania': 'Tanzania', 'Eswatini': 'eSwatini', 
                                                                               "Cote d'Ivoire": "Côte d'Ivoire", 'Serbia and Kosovo: S/RES/1244 (1999)': 'Serbia', 
                                                                               'Venezuela (Bolivarian Republic of)': 'Venezuela', 'Dem. Rep. of the Congo': 'Dem. Rep. Congo', 
                                                                               "Lao People's Dem. Rep.": 'Laos',
                                                                              "South Sudan": "S. Sudan", 
                                                                              "West Sahara": "W. Sahara", 
                                                                              "Bosnia and Herzegovina": "Bosnia and Herz"})

In [ ]:
type(data_2013['origin_country'])

In [ ]:
data_2013['origin_country']

In [ ]:
solutions_2013['origin_country']

In [ ]:
merged_df = pd.merge(data_2013, solutions_2013, on=['origin_country', 'asylum_country', 'year'])

In [ ]:
merged_df.head()

In [9]:
data['origin_country']
# countries_dict = defaultdict(list)
# print(countries_dict.keys())
countries_dict = []

In [11]:
#unique countries 
origin_set = set()
origin_set_2014 = set()
#print(type(origin_set))
for origin in (data_2013["origin_country"]):
    origin_set.add(origin)
    
# for origin in (data_2014["origin_country"]):
#     origin_set_2014.add(origin)
    
print(origin_set)

{'Nigeria', 'Timor-Leste', 'Iraq', 'Eritrea', 'Kenya', 'Vietnam', 'Rwanda', 'Namibia', 'Austria', 'Slovakia', 'Venezuela', 'Central African Rep.', 'Grenada', 'Albania', 'Mauritius', 'Unknown ', 'Latvia', 'Bhutan', 'Finland', 'India', 'Nepal', 'eSwatini', 'Haiti', 'Niger', 'Palestine', 'Chad', 'Armenia', 'Argentina', 'Bolivia', 'Belarus', 'South Korea', 'North Macedonia', 'Burundi', 'Cabo Verde', 'Pakistan', 'Papua New Guinea', 'Comoros', 'Uzbekistan', 'Kuwait', 'Ireland', 'Russia', "Côte d'Ivoire", 'Tunisia', 'Azerbaijan', 'Madagascar', 'Ethiopia', 'Spain', 'Lebanon', 'Netherlands', 'Philippines', 'Kiribati', 'Guinea', 'Tajikistan', 'Palau', 'Morocco', 'Seychelles', 'Hungary', 'Mali', 'Kyrgyzstan', 'United Kingdom', 'New Zealand', 'Cuba', 'Greenland', 'Togo', 'Solomon Islands', 'Guatemala', 'Marshall Islands', 'Saint Lucia', 'Zambia', 'Afghanistan', 'Hong Kong', 'Colombia', 'Sri Lanka', 'Zimbabwe', 'Andorra', 'Iceland', 'Senegal', 'South Africa', 'Equatorial Guinea', 'Czechia', 'Mozambique', 'Cyprus', 'Israel', 'Ecuador', 'Mauritania', 'Congo', 'Yemen', 'Moldova', 'Peru', 'Ghana', 'Bahrain', 'China', 'Burkina Faso', 'Dem. Rep. Congo', 'Mexico', 'Iran', 'Canada', 'Curacao ', 'Thailand', 'Uruguay', 'Tibetan', 'Belgium', 'Greece', 'Ukraine', 'Cambodia', 'Kazakhstan', 'Switzerland', 'Samoa', 'Liberia', 'Laos', 'Gambia', 'Djibouti', 'Bulgaria', 'China, Macao SAR', 'Tonga', 'United Arab Emirates', 'Maldives', 'Indonesia', 'Saudi Arabia', 'Turkey', 'Stateless', 'United States of America', 'Fiji', 'Italy', 'Qatar', 'Libya', 'Angola', 'Sweden', 'Sierra Leone', 'Jordan', 'Uganda', 'Lesotho', 'Tanzania', 'El Salvador', 'Georgia', 'Guinea-Bissau', 'Sao Tome and Principe', 'Montenegro', 'Egypt', 'Somalia', 'Honduras', 'North Korea', 'Western Sahara', 'Germany', 'Singapore', 'Guyana', 'Trinidad and Tobago', 'Saint Vincent and the Grenadines', 'Paraguay', 'Malaysia', 'Nicaragua', 'Portugal', 'Gabon', 'Australia', 'Malta', 'Croatia', 'Turks and Caicos Islands', 'Dominican Rep.', 'Slovenia', 'Bahamas', 'France', 'Panama', 'Cayman Islands', 'Sudan', 'Syria', 'Malawi', 'S. Sudan', 'Chile', 'Brazil', 'Oman', 'Jamaica', 'Botswana', 'Lithuania', 'Bosnia and Herz', 'Belize', 'Benin', 'Algeria', 'Turkmenistan', 'Cameroon', 'Poland', 'Japan', 'Barbados', 'Bangladesh', 'Estonia', 'Mongolia', 'Suriname', 'Niue', 'Monaco', 'Antigua and Barbuda', 'Dominica', 'Norway', 'Romania', 'Myanmar', 'Saint Kitts and Nevis', 'Costa Rica', 'Serbia'}

In [ ]:
#solutions origins set 
soln_origin_set = set()

#print(type(origin_set))
for origin in (solutions_2013["origin_country"]):
    soln_origin_set.add(origin)

print(soln_origin_set)

In [ ]:
merged_df.head()

In [ ]:
#merged file 
merged_dict=[]
for i, origin in enumerate(origin_set):
    merged_dict.append({"country": origin, "destination_countries": [], "destination_refugees": [] , "destination_pairs": [], "destination_a": [], "totals": [], "returned_refugees":[], "naturalized":[], "resettled":[] })
    #print(countries_dict[i]['destination'])
   
    origin_data = merged_df[merged_df['origin_country']==origin]
   
    total_refugees = 0.0
    total_asylum = 0.0
    total_returned = 0.0
    total_resettled = 0.0
    total_naturalized = 0.0
    
    for j, asylum in enumerate(origin_data['asylum_country']):
        
        merged_dict[i]["destination_countries"].append(asylum)
        merged_dict[i]["destination_refugees"].append((float(origin_data["number_refugees"].iloc[j])))
        
        merged_dict[i]["destination_pairs"].append((asylum, float(origin_data["number_refugees"].iloc[j])))
        merged_dict[i]["destination_a"].append({asylum: (float(origin_data["number_asylum"].iloc[j]))})
        
        total_refugees+= float(origin_data["number_refugees"].iloc[j])
        
        total_asylum+= float(origin_data["number_asylum"].iloc[j])
        
        if origin_data["returned_refugees"].iloc[j] >0:
            total_returned+= float(origin_data["returned_refugees"].iloc[j])
        
        if origin_data["resettlement_arrivals"].iloc[j] >0:
        
            total_resettled+= float(origin_data["resettlement_arrivals"].iloc[j])
        
        if origin_data['naturalisation'].iloc[j] >0:
        
            total_naturalized+=float(origin_data['naturalisation'].iloc[j])
   
        
    merged_dict[i]["totals"].append({"total_refugees": total_refugees, "total_asylum": total_asylum})
    merged_dict[i]['returned_refugees'] = total_returned
    
    merged_dict[i]['resettled'] = total_resettled
    merged_dict[i]['naturalized'] = total_naturalized

print(merged_dict[110])

In [12]:
data_2013.head()

,year,origin_country,origin_iso,asylum_country,asylum_iso,number_refugees,number_asylum,idps_concern,venezuelans_displaced,stateless,of_concern
12776,2013,Afghanistan,AFG,Afghanistan,AFG,0,0,631286,NaN,0,275486
12777,2013,Iran,IRN,Afghanistan,AFG,36,16,0,NaN,0,0
12778,2013,Pakistan,PAK,Afghanistan,AFG,16825,45,0,NaN,0,0
12779,2013,Egypt,EGY,Albania,ALB,5,0,0,NaN,0,0
12780,2013,China,CHN,Albania,ALB,12,0,0,NaN,0,0

In [14]:
print(origin_set)

{'Nigeria', 'Timor-Leste', 'Iraq', 'Eritrea', 'Kenya', 'Vietnam', 'Rwanda', 'Namibia', 'Austria', 'Slovakia', 'Venezuela', 'Central African Rep.', 'Grenada', 'Albania', 'Mauritius', 'Unknown ', 'Latvia', 'Bhutan', 'Finland', 'India', 'Nepal', 'eSwatini', 'Haiti', 'Niger', 'Palestine', 'Chad', 'Armenia', 'Argentina', 'Bolivia', 'Belarus', 'South Korea', 'North Macedonia', 'Burundi', 'Cabo Verde', 'Pakistan', 'Papua New Guinea', 'Comoros', 'Uzbekistan', 'Kuwait', 'Ireland', 'Russia', "Côte d'Ivoire", 'Tunisia', 'Azerbaijan', 'Madagascar', 'Ethiopia', 'Spain', 'Lebanon', 'Netherlands', 'Philippines', 'Kiribati', 'Guinea', 'Tajikistan', 'Palau', 'Morocco', 'Seychelles', 'Hungary', 'Mali', 'Kyrgyzstan', 'United Kingdom', 'New Zealand', 'Cuba', 'Greenland', 'Togo', 'Solomon Islands', 'Guatemala', 'Marshall Islands', 'Saint Lucia', 'Zambia', 'Afghanistan', 'Hong Kong', 'Colombia', 'Sri Lanka', 'Zimbabwe', 'Andorra', 'Iceland', 'Senegal', 'South Africa', 'Equatorial Guinea', 'Czechia', 'Mozambique', 'Cyprus', 'Israel', 'Ecuador', 'Mauritania', 'Congo', 'Yemen', 'Moldova', 'Peru', 'Ghana', 'Bahrain', 'China', 'Burkina Faso', 'Dem. Rep. Congo', 'Mexico', 'Iran', 'Canada', 'Curacao ', 'Thailand', 'Uruguay', 'Tibetan', 'Belgium', 'Greece', 'Ukraine', 'Cambodia', 'Kazakhstan', 'Switzerland', 'Samoa', 'Liberia', 'Laos', 'Gambia', 'Djibouti', 'Bulgaria', 'China, Macao SAR', 'Tonga', 'United Arab Emirates', 'Maldives', 'Indonesia', 'Saudi Arabia', 'Turkey', 'Stateless', 'United States of America', 'Fiji', 'Italy', 'Qatar', 'Libya', 'Angola', 'Sweden', 'Sierra Leone', 'Jordan', 'Uganda', 'Lesotho', 'Tanzania', 'El Salvador', 'Georgia', 'Guinea-Bissau', 'Sao Tome and Principe', 'Montenegro', 'Egypt', 'Somalia', 'Honduras', 'North Korea', 'Western Sahara', 'Germany', 'Singapore', 'Guyana', 'Trinidad and Tobago', 'Saint Vincent and the Grenadines', 'Paraguay', 'Malaysia', 'Nicaragua', 'Portugal', 'Gabon', 'Australia', 'Malta', 'Croatia', 'Turks and Caicos Islands', 'Dominican Rep.', 'Slovenia', 'Bahamas', 'France', 'Panama', 'Cayman Islands', 'Sudan', 'Syria', 'Malawi', 'S. Sudan', 'Chile', 'Brazil', 'Oman', 'Jamaica', 'Botswana', 'Lithuania', 'Bosnia and Herz', 'Belize', 'Benin', 'Algeria', 'Turkmenistan', 'Cameroon', 'Poland', 'Japan', 'Barbados', 'Bangladesh', 'Estonia', 'Mongolia', 'Suriname', 'Niue', 'Monaco', 'Antigua and Barbuda', 'Dominica', 'Norway', 'Romania', 'Myanmar', 'Saint Kitts and Nevis', 'Costa Rica', 'Serbia'}

In [15]:
print(data_2013['origin_country'])

12776    Afghanistan
12777           Iran
12778       Pakistan
12779          Egypt
12780          China
            ...
17332           Cuba
17333       Colombia
17334           Cuba
17335        Jamaica
17336           Iran
Name: origin_country, Length: 4561, dtype: object

In [21]:
countries_dict=[]
for i, origin in enumerate(origin_set):
    countries_dict.append({"country": origin, "destination_countries": [], "destination_refugees": [] , "destination_pairs": [], "destination_a": [], "totals": [] })
    #print(countries_dict[i]['destination'])
   
    origin_data = data_2013[data_2013['origin_country']==origin]
   
    total_refugees = 0.0
    total_asylum = 0.0
    
    for j, asylum in enumerate(origin_data['asylum_country']):
        
        if origin_data['number_refugees'].iloc[j] >0:
        
            countries_dict[i]["destination_countries"].append(asylum)
            countries_dict[i]["destination_refugees"].append((float(origin_data["number_refugees"].iloc[j])))
        
            
            countries_dict[i]["destination_pairs"].append((asylum, float(origin_data["number_refugees"].iloc[j])))
        countries_dict[i]["destination_a"].append({asylum: (float(origin_data["number_asylum"].iloc[j]))})
        
        total_refugees+= float(origin_data["number_refugees"].iloc[j])
        
        total_asylum+= float(origin_data["number_asylum"].iloc[j])
        
        #print(origin_data['number_refugees'].iloc[j])
        
    countries_dict[i]["totals"].append({"total_refugees": total_refugees, "total_asylum": total_asylum})
    #countries_dict[i]["totals"] = total_refugees, 

print(countries_dict[0]['destination_pairs'])

[('Argentina', 50.0), ('Australia', 132.0), ('Austria', 346.0), ('Belgium', 23.0), ('Brazil', 55.0), ('Bulgaria', 8.0), ('Canada', 4441.0), ('Chad', 553.0), ('Chile', 5.0), ('Cameroon', 7459.0), ('Congo', 5.0), ('Costa Rica', 28.0), ('Cyprus', 5.0), ('Czechia', 13.0), ('Greenland', 14.0), ('Ecuador', 25.0), ('Ethiopia', 5.0), ('Finland', 115.0), ('France', 988.0), ('United Kingdom', 1244.0), ('Germany', 720.0), ('Ghana', 5.0), ('Greece', 103.0), ('Guinea', 5.0), ('Hungary', 24.0), ("Côte d'Ivoire", 19.0), ('Ireland', 477.0), ('Israel', 5.0), ('Italy', 4192.0), ('South Korea', 7.0), ('Lithuania', 5.0), ('Luxembourg', 5.0), ('Mexico', 18.0), ('Morocco', 5.0), ('Malta', 21.0), ('Netherlands', 225.0), ('Niger', 8385.0), ('Norway', 176.0), ('Panama', 10.0), ('Peru', 9.0), ('Poland', 18.0), ('Portugal', 18.0), ('Romania', 7.0), ('South Africa', 34.0), ('Senegal', 7.0), ('Spain', 22.0), ('Sweden', 257.0), ('Switzerland', 113.0), ('Togo', 8.0), ('Turkey', 5.0), ('Ukraine', 5.0), ('Uruguay', 11.0), ('USA', 733.0), ('Venezuela', 5.0)]

In [ ]:
sorted_2013_refugees = sorted(countries_dict, key = lambda k: k['totals'], reverse=True)
print(sorted_2013_refugees[9])

In [ ]:
solutions_2013.head()

In [ ]:
countries_solutions_dict = []

for i, origin in enumerate(soln_origin_set):
    countries_solutions_dict.append({"country": origin, "destination_countries": [], "returned_refugees": [] , "resettlement": [], "naturalized": [] })
    #print(countries_dict[i]['destination'])
   
    origin_data = solutions_2013[solutions_2013['origin_country']==origin]
   
    total_returned = 0.0
    total_resettled = 0.0
    total_naturalized = 0.0
    
    for j, asylum in enumerate(origin_data['asylum_country']):
        
        countries_solutions_dict[i]["destination_countries"].append(asylum)
#         countries_dict[i]["returned_refugees"].append((float(origin_data["number_refugees"].iloc[j])))
        
#         countries_dict[i]["destination_pairs"].append((asylum, float(origin_data["number_refugees"].iloc[j])))
#         countries_dict[i]["destination_a"].append({asylum: (float(origin_data["number_asylum"].iloc[j]))})
        if origin_data["returned_refugees"].iloc[j] >0:
            total_returned+= float(origin_data["returned_refugees"].iloc[j])
        
        if origin_data["resettlement_arrivals"].iloc[j] >0:
        
            total_resettled+= float(origin_data["resettlement_arrivals"].iloc[j])
        
        if origin_data['naturalisation'].iloc[j] >0:
        
            total_naturalized+=float(origin_data['naturalisation'].iloc[j])
        
        #print(origin_data['number_refugees'].iloc[j])
        
    #countries_solutions_dict[i]["totals"].append({"total_refugees": total_refugees, "total_asylum": total_asylum})

    countries_solutions_dict[i]['returned_refugees'] = total_returned
    
    countries_solutions_dict[i]['resettlement'] = total_resettled
    countries_solutions_dict[i]['naturalized'] = total_naturalized

In [ ]:
#print(countries_solutions_dict)

In [ ]:
#print(countries_solutions_dict[0].get('returned_refugees'))

sorted_returned = sorted(countries_solutions_dict, key = lambda k: k['returned_refugees'], reverse=True)
print(sorted_returned)

In [ ]:
# countries_dict_2014=[]
# for i, origin in enumerate(origin_set_2014):
#     countries_dict_2014.append({"country": origin, "destination_countries":[], "destination_r": [] ,"destination_a": [], "totals": [] })
#     #print(countries_dict[i]['destination'])
   
#     origin_data = data_2014[data_2014['origin_country']==origin]
   
#     total_refugees = 0.0
#     total_asylum = 0.0
    
#     for j, asylum in enumerate(origin_data['asylum_country']):
        
#         countries_dict_2014[i]["destination_countries"].append(asylum)
#         countries_dict_2014[i]["destination_r"].append({asylum: (float(origin_data["number_refugees"].iloc[j]))})
#         countries_dict_2014[i]["destination_a"].append({asylum: (float(origin_data["number_asylum"].iloc[j]))})
        
#         total_refugees+= float(origin_data["number_refugees"].iloc[j])
        
#         total_asylum+= float(origin_data["number_asylum"].iloc[j])
        
#         #print(origin_data['number_refugees'].iloc[j])
        
#     countries_dict_2014[i]["totals"].append({"total_refugees": total_refugees, "total_asylum": total_asylum})
#     #countries_dict_2014[i]["destination_r"] = sorted(countries_dict_2014[i]["destination_r"], key = lambda x:x[0], reverse=True)
    


# print(countries_dict_2014)

In [ ]:
sorted_naturalized = sorted(countries_solutions_dict, key = lambda k: k['naturalized'], reverse=True)
print(sorted_naturalized)

In [ ]:
sorted_resettlement = sorted(countries_solutions_dict, key = lambda k: k['resettlement'], reverse=True)
print(sorted_resettlement)

In [ ]:
#res2014 = str(countries_dict_2014)[1:-1]
#print(res2014)

In [ ]:
# with open('countries-2013-1.json', 'w') as f: 
#     json.dump(res2013,f)

In [ ]:
# with open('countries-2014-1.json', 'w') as f: 
#     json.dump(res2014,f)

In [18]:
with open('countries-2013-updated.json', 'w') as f: 
    json.dump(countries_dict,f)

In [ ]:
# with open('countries-2014-new.json', 'w') as f: 
#     json.dump(countries_dict_2014,f)

In [ ]:
# with open('solutions-2013-sorted.json', 'w') as f: 
#     json.dump(sorted_returned ,f)