In [1]:
import json

import matplotlib.pyplot as plt
import os
import pandas as pd
import numpy as np
from   collections import defaultdict
import string

In [2]:
data_2013_file= 'datasets/countries-2013-updated.json'
solutions2013_file = 'datasets/solutions-2013-sorted.json'

In [3]:
data2013_json = pd.read_json(data_2013_file)

solutions2013_json = pd.read_json(solutions2013_file)

In [4]:
data2013_json.head()

,country,destination_countries,destination_refugees,destination_pairs,destination_a,totals
0,Greece,"[Canada, Germany, United States of America]","[18.0, 46.0, 24.0]","[[Canada, 18.0], [Germany, 46.0], [United Stat...","[{'Canada': 79.0}, {'Germany': 0.0}, {'United ...",[88.0]
1,Saint Vincent and the Grenadines,"[Canada, United Kingdom of Great Britain and N...","[1524.0, 6.0, 5.0]","[[Canada, 1524.0], [United Kingdom of Great Br...","[{'Canada': 223.0}, {'United Kingdom of Great ...",[1535.0]
2,Bhutan,"[Brazil, Canada, Denmark, France, United Kingd...","[29.0, 22.0, 5.0, 102.0, 97.0, 31.0, 5.0, 3097...","[[Brazil, 29.0], [Canada, 22.0], [Denmark, 5.0...","[{'Belgium': 5.0}, {'Brazil': 9.0}, {'Canada':...",[31556.0]
3,Morocco,"[Australia, Austria, Belgium, Brazil, Canada, ...","[18.0, 15.0, 27.0, 5.0, 173.0, 5.0, 7.0, 5.0, ...","[[Australia, 18.0], [Austria, 15.0], [Belgium,...","[{'Egypt': 5.0}, {'Argentina': 5.0}, {'Austral...",[1290.0]
4,Ecuador,"[Argentina, Australia, Brazil, Canada, Chile, ...","[15.0, 5.0, 57.0, 216.0, 18.0, 8.0, 5.0, 5.0, ...","[[Argentina, 15.0], [Australia, 5.0], [Brazil,...","[{'Argentina': 0.0}, {'Australia': 0.0}, {'Bra...",[711.0]

In [9]:
solutions2013_json = solutions2013_json.drop('destination_countries', axis=1)

In [10]:
merged_df = pd.merge(data2013_json, solutions2013_json, on='country')

In [11]:
merged_df.sample(10)

,country,destination_countries,destination_refugees,destination_pairs,destination_a,totals,returned_refugees,resettlement,naturalized
8,Liberia,"[Angola, Egypt, Argentina, Australia, Austria,...","[160.0, 5.0, 69.0, 23.0, 26.0, 17.0, 258.0, 13...","[[Angola, 160.0], [Egypt, 5.0], [Argentina, 69...","[{'Angola': 328.0}, {'Egypt': 5.0}, {'Argentin...",[17548.0],83,115,308
79,Russia,"[Egypt, Argentina, Australia, Austria, Azerbai...","[11.0, 61.0, 66.0, 19577.0, 657.0, 2177.0, 5.0...","[[Egypt, 11.0], [Argentina, 61.0], [Australia,...","[{'Egypt': 54.0}, {'Argentina': 20.0}, {'Austr...",[74310.0],0,98,601
26,Angola,"[Algeria, Argentina, Austria, Belgium, Brazil,...","[5.0, 13.0, 157.0, 67.0, 1062.0, 650.0, 9.0, 1...","[[Algeria, 5.0], [Argentina, 13.0], [Austria, ...","[{'Algeria': 0.0}, {'Egypt': 5.0}, {'Argentina...",[10274.0],1665,6,18
4,South Africa,"[Argentina, Australia, Austria, Brazil, Canada...","[5.0, 32.0, 5.0, 5.0, 45.0, 5.0, 23.0, 125.0, ...","[[Argentina, 5.0], [Australia, 32.0], [Austria...","[{'Argentina': 0.0}, {'Australia': 21.0}, {'Au...",[424.0],0,5,0
90,Jordan,"[Australia, Austria, Belgium, Bulgaria, Canada...","[90.0, 13.0, 27.0, 5.0, 414.0, 16.0, 6.0, 5.0,...","[[Australia, 90.0], [Austria, 13.0], [Belgium,...","[{'Egypt': 9.0}, {'Australia': 97.0}, {'Austri...",[1622.0],0,84,0
75,Mozambique,"[Australia, Canada, France, United Kingdom of ...","[5.0, 6.0, 12.0, 5.0, 11.0, 7.0, 5.0]","[[Australia, 5.0], [Canada, 6.0], [France, 12....","[{'Australia': 0.0}, {'Canada': 0.0}, {'France...",[51.0],0,31,0
9,Kenya,"[Egypt, Australia, Austria, Belgium, Botswana,...","[6.0, 58.0, 27.0, 29.0, 5.0, 1019.0, 7.0, 9.0,...","[[Egypt, 6.0], [Australia, 58.0], [Austria, 27...","[{'Egypt': 0.0}, {'Australia': 49.0}, {'Austri...",[8580.0],0,110,11
54,Tunisia,"[Australia, Austria, Belgium, Bulgaria, Canada...","[6.0, 8.0, 5.0, 5.0, 202.0, 199.0, 34.0, 94.0,...","[[Australia, 6.0], [Austria, 8.0], [Belgium, 5...","[{'Egypt': 9.0}, {'Australia': 0.0}, {'Austria...",[1359.0],0,0,7
80,Central African Rep.,"[Angola, Belgium, Benin, Burkina Faso, Brazil,...","[13.0, 10.0, 11.0, 18.0, 5.0, 64.0, 80545.0, 1...","[[Angola, 13.0], [Belgium, 10.0], [Benin, 11.0...","[{'Angola': 33.0}, {'Belgium': 6.0}, {'Benin':...",[252854.0],0,469,11
69,Kazakhstan,"[Argentina, Australia, Austria, Belgium, Canad...","[22.0, 5.0, 49.0, 33.0, 149.0, 193.0, 7.0, 444...","[[Argentina, 22.0], [Australia, 5.0], [Austria...","[{'Egypt': 5.0}, {'Argentina': 0.0}, {'Austral...",[2114.0],0,5,0

In [35]:
origin_data = merged_df[merged_df['country']=="Liberia"]
print(origin_data.iloc[0]['destination_countries'])

['Angola', 'Egypt', 'Argentina', 'Australia', 'Austria', 'Belgium', 'Brazil', 'Canada', 'Central African Rep.', 'Chad', 'Cameroon', 'Dem. Rep. of the Congo', 'Colombia', 'Costa Rica', 'Czechia', 'Ecuador', 'Finland', 'France', 'Gabon', 'Gambia', 'United Kingdom of Great Britain and Northern Ireland', 'Germany', 'Ghana', 'Guinea-Bissau', 'Guinea', "Cote d'Ivoire", 'Ireland', 'Italy', 'Rep. of Korea', 'Libya', 'Malaysia', 'Netherlands', 'Nigeria', 'Norway', 'Panama', 'Portugal', 'South Africa', 'Saudi Arabia', 'Senegal', 'Sierra Leone', 'Spain', 'Eswatini', 'Sweden', 'Switzerland', 'Turkey', 'Ukraine', 'United States of America', 'Venezuela (Bolivarian Republic of)', 'Zambia']

In [43]:
merged_dict=[]
for i, country in enumerate(merged_df['country']):
    origin_data = merged_df[merged_df['country']==country]
    
    merged_dict.append({"country": country, "destination_countries": [], 
                        "destination_refugees": [] , 
                        "destination_pairs": [], 
                        "totals": [] })

#     total_refugees = 0.0
#     total_asylum = 0.0
#     total_returned = 0.0
#     total_resettled = 0.0
#     total_naturalized = 0.0
    
    
    merged_dict[i]["destination_countries"] = merged_df.iloc[i]['destination_countries']
    
    merged_dict[i]["destination_refugees"] = merged_df.iloc[i]['destination_refugees']
    
    merged_dict[i]["destination_pairs"] = merged_df.iloc[i]['destination_pairs']
    
    merged_dict[i]["totals"] = merged_df.iloc[i]['totals']
    merged_dict[i]['returned_refugees'] = merged_df.iloc[i]['returned_refugees']
    
    merged_dict[i]['resettled'] = merged_df.iloc[i]['resettlement']
    merged_dict[i]['naturalized'] = merged_df.iloc[i]['naturalized']
    
    
print(merged_dict[0])

TypeError: float() argument must be a string or a number, not 'list'

In [40]:
with open('merged_2013.json', 'w') as f: 
    json.dump(merged_dict,f)

TypeError: Object of type int64 is not JSON serializable